services:
  loudness_correction: 
    build:
      target: loudness_correction
    networks:
      - local_network
    # Use the timezone settings of the host machine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mountpoint:/mountpoint:rw
  progress_report: 
    build:
      target: progress_report
    networks:
      - local_network
    ports:
      - 9000:9000
  heartbeat_checker: 
    build:
      target: heartbeat_checker
    networks:
      - local_network
    # Use the timezone settings of the host machine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  local_network:
